add_lunch_combo cm_Cloud_Q11-eng
add_lunch_combo cm_Cloud_Q11-user
add_lunch_combo cm_Cloud_Q11-userdebug

#add_lunch_combo lineage_Cloud_Q11-eng
#add_lunch_combo lineage_Cloud_Q11-user
#add_lunch_combo lineage_Cloud_Q11-userdebug
